version: "3"

services:
    # product-buyer:
    #     build: .
    #     env_file:
    #         - .env
    arangodb_db_container:
        image: arangodb
        environment:
            ARANGO_ROOT_PASSWORD: localtest
        ports:
            - 8529:8529
        volumes:
            - arangodb_data_container:/var/lib/arangodb3
            - arangodb_apps_data_container:/var/lib/arangodb3-apps

volumes:
    arangodb_data_container:
    arangodb_apps_data_container:
